// <auto-generated />
using System;
using ITSolution.Framework.Core.CustomUserAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITSolution.Framework.Servers.Core.CustomerApi.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20210709170057_CustomerCreate")]
    partial class CustomerCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ITSolution.Framework.Servers.Core.CustomerApi.Model.Customer", b =>
                {
                    b.Property<int>("IdCliFor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abertura")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CapitalSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSituacao")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSituacaoEspecial")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DtCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DtRegtroJuntaCom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Efr")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoSituacao")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NaturezaJuridica")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEndereco")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroEndereco")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoEspecial")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("SituacaoJuridica")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusCliente")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneComercial")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEndereco")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliFor");

                    b.ToTable("CliFor");
                });
#pragma warning restore 612, 618
        }
    }
}
